/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AnnexesRouteImport } from './routes/annexes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as GlossaireRouteImport } from './routes/glossaire'
import { Route as LiensUtilesRouteImport } from './routes/liens-utiles'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as ReferencesRouteImport } from './routes/references'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedBibliothequeRouteImport } from './routes/_authenticated/bibliotheque'
import { Route as AuthenticatedCertificationsRouteImport } from './routes/_authenticated/certifications'
import { Route as AuthenticatedCpdRouteImport } from './routes/_authenticated/cpd'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedParametresRouteImport } from './routes/_authenticated/parametres'
import { Route as AuthenticatedPlanningRouteImport } from './routes/_authenticated/planning'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedQuizRouteImport } from './routes/_authenticated/quiz'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedAssistantIndexRouteImport } from './routes/_authenticated/assistant.index'
import { Route as AuthenticatedAssistantThreadIdRouteImport } from './routes/_authenticated/assistant.$threadId'
import { Route as AuthenticatedSeanceModuleIdRouteImport } from './routes/_authenticated/seance.$moduleId'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnexesRoute = AnnexesRouteImport.update({
  id: '/annexes',
  path: '/annexes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaireRoute = GlossaireRouteImport.update({
  id: '/glossaire',
  path: '/glossaire',
  getParentRoute: () => rootRouteImport,
} as any)
const LiensUtilesRoute = LiensUtilesRouteImport.update({
  id: '/liens-utiles',
  path: '/liens-utiles',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesRoute = ReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBibliothequeRoute =
  AuthenticatedBibliothequeRouteImport.update({
    id: '/bibliotheque',
    path: '/bibliotheque',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCertificationsRoute =
  AuthenticatedCertificationsRouteImport.update({
    id: '/certifications',
    path: '/certifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCpdRoute = AuthenticatedCpdRouteImport.update({
  id: '/cpd',
  path: '/cpd',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParametresRoute = AuthenticatedParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanningRoute = AuthenticatedPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuizRoute = AuthenticatedQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAssistantIndexRoute =
  AuthenticatedAssistantIndexRouteImport.update({
    id: '/assistant/',
    path: '/assistant/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssistantThreadIdRoute =
  AuthenticatedAssistantThreadIdRouteImport.update({
    id: '/assistant/$threadId',
    path: '/assistant/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSeanceModuleIdRoute =
  AuthenticatedSeanceModuleIdRouteImport.update({
    id: '/seance/$moduleId',
    path: '/seance/$moduleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/annexes': typeof AnnexesRoute
  '/auth': typeof AuthRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/cookies': typeof CookiesRoute
  '/glossaire': typeof GlossaireRoute
  '/liens-utiles': typeof LiensUtilesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/references': typeof ReferencesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bibliotheque': typeof AuthenticatedBibliothequeRoute
  '/certifications': typeof AuthenticatedCertificationsRoute
  '/cpd': typeof AuthenticatedCpdRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/planning': typeof AuthenticatedPlanningRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/quiz': typeof AuthenticatedQuizRoute
  '/api/chat': typeof ApiChatRoute
  '/assistant/$threadId': typeof AuthenticatedAssistantThreadIdRoute
  '/seance/$moduleId': typeof AuthenticatedSeanceModuleIdRoute
  '/assistant/': typeof AuthenticatedAssistantIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/annexes': typeof AnnexesRoute
  '/auth': typeof AuthRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/cookies': typeof CookiesRoute
  '/glossaire': typeof GlossaireRoute
  '/liens-utiles': typeof LiensUtilesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/references': typeof ReferencesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bibliotheque': typeof AuthenticatedBibliothequeRoute
  '/certifications': typeof AuthenticatedCertificationsRoute
  '/cpd': typeof AuthenticatedCpdRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/planning': typeof AuthenticatedPlanningRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/quiz': typeof AuthenticatedQuizRoute
  '/api/chat': typeof ApiChatRoute
  '/assistant/$threadId': typeof AuthenticatedAssistantThreadIdRoute
  '/seance/$moduleId': typeof AuthenticatedSeanceModuleIdRoute
  '/assistant': typeof AuthenticatedAssistantIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/annexes': typeof AnnexesRoute
  '/auth': typeof AuthRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/cookies': typeof CookiesRoute
  '/glossaire': typeof GlossaireRoute
  '/liens-utiles': typeof LiensUtilesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/references': typeof ReferencesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/bibliotheque': typeof AuthenticatedBibliothequeRoute
  '/_authenticated/certifications': typeof AuthenticatedCertificationsRoute
  '/_authenticated/cpd': typeof AuthenticatedCpdRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/parametres': typeof AuthenticatedParametresRoute
  '/_authenticated/planning': typeof AuthenticatedPlanningRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/quiz': typeof AuthenticatedQuizRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/assistant/$threadId': typeof AuthenticatedAssistantThreadIdRoute
  '/_authenticated/seance/$moduleId': typeof AuthenticatedSeanceModuleIdRoute
  '/_authenticated/assistant/': typeof AuthenticatedAssistantIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/annexes'
    | '/auth'
    | '/cgu'
    | '/confidentialite'
    | '/cookies'
    | '/glossaire'
    | '/liens-utiles'
    | '/mentions-legales'
    | '/references'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/bibliotheque'
    | '/certifications'
    | '/cpd'
    | '/dashboard'
    | '/parametres'
    | '/planning'
    | '/profil'
    | '/quiz'
    | '/api/chat'
    | '/assistant/$threadId'
    | '/seance/$moduleId'
    | '/assistant/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/annexes'
    | '/auth'
    | '/cgu'
    | '/confidentialite'
    | '/cookies'
    | '/glossaire'
    | '/liens-utiles'
    | '/mentions-legales'
    | '/references'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/bibliotheque'
    | '/certifications'
    | '/cpd'
    | '/dashboard'
    | '/parametres'
    | '/planning'
    | '/profil'
    | '/quiz'
    | '/api/chat'
    | '/assistant/$threadId'
    | '/seance/$moduleId'
    | '/assistant'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/annexes'
    | '/auth'
    | '/cgu'
    | '/confidentialite'
    | '/cookies'
    | '/glossaire'
    | '/liens-utiles'
    | '/mentions-legales'
    | '/references'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/bibliotheque'
    | '/_authenticated/certifications'
    | '/_authenticated/cpd'
    | '/_authenticated/dashboard'
    | '/_authenticated/parametres'
    | '/_authenticated/planning'
    | '/_authenticated/profil'
    | '/_authenticated/quiz'
    | '/api/chat'
    | '/_authenticated/assistant/$threadId'
    | '/_authenticated/seance/$moduleId'
    | '/_authenticated/assistant/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AnnexesRoute: typeof AnnexesRoute
  AuthRoute: typeof AuthRoute
  CguRoute: typeof CguRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  CookiesRoute: typeof CookiesRoute
  GlossaireRoute: typeof GlossaireRoute
  LiensUtilesRoute: typeof LiensUtilesRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  ReferencesRoute: typeof ReferencesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annexes': {
      id: '/annexes'
      path: '/annexes'
      fullPath: '/annexes'
      preLoaderRoute: typeof AnnexesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossaire': {
      id: '/glossaire'
      path: '/glossaire'
      fullPath: '/glossaire'
      preLoaderRoute: typeof GlossaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liens-utiles': {
      id: '/liens-utiles'
      path: '/liens-utiles'
      fullPath: '/liens-utiles'
      preLoaderRoute: typeof LiensUtilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references': {
      id: '/references'
      path: '/references'
      fullPath: '/references'
      preLoaderRoute: typeof ReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bibliotheque': {
      id: '/_authenticated/bibliotheque'
      path: '/bibliotheque'
      fullPath: '/bibliotheque'
      preLoaderRoute: typeof AuthenticatedBibliothequeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certifications': {
      id: '/_authenticated/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof AuthenticatedCertificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cpd': {
      id: '/_authenticated/cpd'
      path: '/cpd'
      fullPath: '/cpd'
      preLoaderRoute: typeof AuthenticatedCpdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parametres': {
      id: '/_authenticated/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AuthenticatedParametresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planning': {
      id: '/_authenticated/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof AuthenticatedPlanningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quiz': {
      id: '/_authenticated/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof AuthenticatedQuizRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assistant/': {
      id: '/_authenticated/assistant/'
      path: '/assistant'
      fullPath: '/assistant/'
      preLoaderRoute: typeof AuthenticatedAssistantIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant/$threadId': {
      id: '/_authenticated/assistant/$threadId'
      path: '/assistant/$threadId'
      fullPath: '/assistant/$threadId'
      preLoaderRoute: typeof AuthenticatedAssistantThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seance/$moduleId': {
      id: '/_authenticated/seance/$moduleId'
      path: '/seance/$moduleId'
      fullPath: '/seance/$moduleId'
      preLoaderRoute: typeof AuthenticatedSeanceModuleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBibliothequeRoute: typeof AuthenticatedBibliothequeRoute
  AuthenticatedCertificationsRoute: typeof AuthenticatedCertificationsRoute
  AuthenticatedCpdRoute: typeof AuthenticatedCpdRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedParametresRoute: typeof AuthenticatedParametresRoute
  AuthenticatedPlanningRoute: typeof AuthenticatedPlanningRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedQuizRoute: typeof AuthenticatedQuizRoute
  AuthenticatedAssistantThreadIdRoute: typeof AuthenticatedAssistantThreadIdRoute
  AuthenticatedSeanceModuleIdRoute: typeof AuthenticatedSeanceModuleIdRoute
  AuthenticatedAssistantIndexRoute: typeof AuthenticatedAssistantIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBibliothequeRoute: AuthenticatedBibliothequeRoute,
  AuthenticatedCertificationsRoute: AuthenticatedCertificationsRoute,
  AuthenticatedCpdRoute: AuthenticatedCpdRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedParametresRoute: AuthenticatedParametresRoute,
  AuthenticatedPlanningRoute: AuthenticatedPlanningRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedQuizRoute: AuthenticatedQuizRoute,
  AuthenticatedAssistantThreadIdRoute: AuthenticatedAssistantThreadIdRoute,
  AuthenticatedSeanceModuleIdRoute: AuthenticatedSeanceModuleIdRoute,
  AuthenticatedAssistantIndexRoute: AuthenticatedAssistantIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AnnexesRoute: AnnexesRoute,
  AuthRoute: AuthRoute,
  CguRoute: CguRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  CookiesRoute: CookiesRoute,
  GlossaireRoute: GlossaireRoute,
  LiensUtilesRoute: LiensUtilesRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  ReferencesRoute: ReferencesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
